### ISSUE TITLE
Bug with BottomNavigationBar

### ISSUE THREAD

**Issue by antorne99** [andreciornavei/flutter-input-sheet#3] opened 2020-05-19 15:20 UTC
Hi man i have a problem with your plugin.
Basically, I have a bottomNavigationBar defined into my Scaffold, but when i try to edit an input sheet, this bottomNavigationBar seems to have priority and, then, it goes above your component.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/49185210/82344804-c9818500-99f4-11ea-9d9d-0ca149170855.gif)

Thanks in advance

**Comment by andreciornavei** [comment] 2020-05-19 15:56
i see, this should not happen, because the piece of code below tells to component to render a blank space height with same size of keyboard, but i will find alternatives to this approach. Could you send to me the device model of yours emulator to reproduce this bug here?

![Captura de Tela 2020-05-19 às 12 49 05](https://user-images.githubusercontent.com/19330855/82348335-1a7e8280-99cf-11ea-8085-f697b441e59f.png)

**Comment by antorne99** [comment] 2020-05-19 16:06
My emulator is Pixel 3

**Comment by antorne99** [comment] 2020-05-19 16:11
Maybe, i didn't explain the problem very well.
The bottomBar is defined in a parent component, while the input sheets are defined in a child component. So in the body of parent component, i show the children.

Could this be the problem?

**Comment by andreciornavei** [comment] 2020-05-19 16:20
Maybe yes, meybe the parent component affect the Keyboard widget tree, but the problem still have to be fixed in this piece of code... I will create another sample project to reproduce this issue with bottomBar to be fixes as soon as possible.

**Comment by antorne99** [comment] 2020-05-19 16:37
Ok, i'll wait your next release

**Comment by andreciornavei** [comment] 2020-05-20 02:46
Great news, i released a new version with this bug fix `0.1.1`.
Give me the feedback if it works for you then i close this issue ok?

**Comment by antorne99** [comment] 2020-05-20 06:08
Nice job, dude. It works perfectly,
Thank you so much

**Comment by andreciornavei** [comment] 2020-05-20 14:20
Perfect, thank you to report and help it to be better.

**Closed as completed by andreciornavei** 2020-05-20 14:20 UTC
